### ISSUE TITLE
Signed call not working

### ISSUE THREAD

**Issue by seanbrhn3** [duosecurity/duo_api_golang#32]
Hi Duo team,

I've been trying to create admins using your Signed call function but I've been running into some errors. I pulled your code and pass in my information like so ```
	par := url.Values{}
        par.Set("name", "TestName")
	par.Set("email", "test@test.com")
	resp, _, err := duo.SignedCall("POST", "/admin/v1/admins", par)```
problem is I get a 40103 error 

```{
    "code": 40103,
    "message": "Invalid signature in request credentials",
    "stat": "FAIL"
}```

I checked the sign function that creates the hmac signature 
and the conanicalized information is this 

```Mon, 05 Apr 2021 18:21:16 +0000
POST
api-xxxxxxxx.duosecurity.com
/admin/v1/admins
email=test%40test.com&name=TestName```
it  seems write but that hmac signature I get generated is wrong I've even tested on an online hmac generator and they don't match up. I haven't modified your code so I'm not sure where the error is coming from

**Comment by james-d-elliott** [comment]
@seanbrhn3 what was the cause of this?
