### ISSUE TITLE
Missing e.g. AuthHostname

### ISSUE THREAD

**Issue by johnnybubonic** [duosecurity/duo_api_golang#33]
In methods such as [Preauth](https://pkg.go.dev/github.com/duosecurity/duo_api_golang@v0.0.0-20201112143038-0e07e9f869e3/authapi#AuthApi.Preauth), there currently exists no in-library way of adding the [`hostname` parameter](https://duo.com/docs/authapi#/preauth) as there does with other parameters (e.g. `authapi.PreauthIpAddr()`).

**Comment by johnnybubonic** [comment]
...bump?

**Comment by AaronAtDuo** [comment]
Closing out old tickets
